### ISSUE TITLE
Update or remove the 12factor app reference

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-flex#18]
12factor app is a sample of a company deciding for what shall be Macro Architecture aspects. Yet, as their flight level varies they are not exactly the best example. If we don't find a better example in the wild, we should rather remove them.

**Comment by ewolff** [comment]
There is https://isa-principles.org/

**Comment by mikesperber** [comment]
I'm all for removing it.

**Comment by mrtnlhmnn** [comment]
Yes, agree. Let's get rid of it. (If a training still wants to mention it, this does not harm, but it should not be a "must have" in the curriculum
