### ISSUE TITLE
Update Reference: 2nd edition of Sam Newmann: Building Microservices

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-flex#22]
There is a new edition available of thebBook 
* [Sam Newman 2015] Sam Newmann: Building Microservices: Designung Fine-Grained Systems, O’Reilly Media, 2015

New edition:

* [Sam Newman 2021] Sam Newmann: Building Microservices: Designung Fine-Grained Systems, O'Reilly Media; 2nd edition 2021

(in the references, /docs/99-references)/00-references.adoc)

**Comment by sippsack** [comment]
Solved with commit 59d04b782651008e2d9544bc095c29bd256ab332 beside some other smaller fixes in the references.
