### ISSUE TITLE
Explicitly formulated learning goals

### ISSUE THREAD

**Issue by StefanZoerner** [isaqb-org/curriculum-flex#24]
The old curriculum still has the "Can", "Understand" "Know" structure from the exam relevant topics as we know them in Foundation (R1, R2, R3). It would be nice if there were explicitly formulated learning goals as we have in the newer curricula. 

One can find this nicely elaborated in the new DDD curriculum. Example:

* LG 6-6: Be able to use Domain Events as a means of communication between Bounded Contexts

**Comment by aheusingfeld** [comment]
Fixed with #68, #69, #70, #71, #72, and #73
