### ISSUE TITLE
move chapter 8's content to "integration"

### ISSUE THREAD

**Issue by mrtnlhmnn** [isaqb-org/curriculum-flex#46]
Chapter 8 ("Ausblick") contains two topics: "Consistency" and "Resilience".

This is a bit weird and looks like "Let's put a few extra topics" to the final chapter. 

Actually these two topics are super important and should be moved to the chapter "Integration", as in a distributed application one needs to care for these concepts.

**Comment by aburmeis** [comment]
Even if resilience is not only a topic of integration I like the idea much more than the outlook approach which has a touch of optional which it should not. Another idea could be to move the copter up (after integration) with a different name (maybe simply _consistency and resilience_) to keep the integration chapter in a proper size.

**Comment by mrtnlhmnn** [comment]
Absolutely ok for me as well
