### ISSUE TITLE
Verstümmelter Satz in englischer Übersetzung in 3.2.2

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-flex#5]
"Some specifications should better be superior valid for the integration with other building blocks of this type, in general."

Vorschlag:

"Some specifications should apply at a higher level and more broadly for the integration with other building blocks of this type."

Der Begriff "specification" in dem Absatz ist generell problematisch, weil er in der Informatik oft anders verwendet wird. Besser wäre so etwas:

"It can be useful to establish standards for the development of a module; different levels of standardization may be useful. Some standards should hold at a higher level, and apply more broadly for the integration with other building blocks of a certain type."

**Comment by ewolff** [comment]
I fixes the translation in 18f187916fb8c1fc78b1ce0d696d1e3d1f1e4690 . I kept it more closely to the German version. Please reopen if you feel that the problem is not solved. Thanks.
