### ISSUE TITLE
Rewrite introduction chapter

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-flex#51]
the introduction to "What you will learn in FLEX" has to be updated according to the new structure.

At the same time, clarify that case study is not a dedicated chapter but shall be present in all chapters and should be incorporated into the practice sessions of each chapter. Thus having a separate chapter mentioning dedicated practice time is superfluous.

We thus remove the chapter and introduce the MUST-have requirement for trainers to lead through the training by using a practical case study.

**Comment by mrtnlhmnn** [comment]
How is this done in other curricula? This is not a FLEX-specific thing, right?

I do not see a need to change this now (or at all)

**Comment by aheusingfeld** [comment]
It is a FLEX specific thing. The other curricula did not introduce a dedicated chapter for "case study" but stated that each chapter shall have exercises. And e.g. DDD explicitly states that the curriculum does not want to define the examples or exercises: https://public.isaqb.org/curriculum-ddd/curriculum-ddd-de.html#_dauer_didaktik_und_weitere_details

**Comment by mrtnlhmnn** [comment]
OK, than so be it. It should be handle consistently in all curricula.

**Comment by aheusingfeld** [comment]
Fixed with 09b769334be3278ee6c138fa358a8b33771843c4
