### ISSUE TITLE
Rewrite chapter 1: 

### ISSUE THREAD

**Issue by sippsack** [isaqb-org/curriculum-flex#56]
see https://github.com/isaqb-org/curriculum-flex/wiki

Chapter 1: WHY approach Flexible Systems

* How to find out the long-term quality goals for the system you build
* Quality Goals that later on justify architectural decisions
* Quality Scenarios as executable (architecture) tests (Fitness functions)
* Principles
** Focus on Customer Value
** Build for Replacement: The difference between service implementation and service functionality
** Interfaces, Interactions, Information: Integration Points are relationships between humans
** Establish Feedback Loops: Build-Measure-Learn
** Start with the end in mind: What operations model can your organisation handle?
** Quality vs. Quantity: Prioritize SLOs/Error Budget against Feature Development

**Comment by aheusingfeld** [comment]
Fixed with #74
