### ISSUE TITLE
Review current version 2020.1-rev1

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/curriculum-flex#7]
Please review the current status (DE version only). 

I already started to split some of the learning goals (like in https://github.com/isaqb-org/curriculum-ddd/blob/master/docs/03-module-block-3/02-learning-goals.adoc) but stopped because I wasn't sure whether we want to do that in one step (which would change the version of the document to 2020.1) or rather a second step in order to first migrate 1:1 to github, have a version 2015.1, and afterwards rework the learning goals. Please let me know your thoughts.

**Comment by ewolff** [comment]
Thanks. I have checked it and done some adjustments. I don't see the value in migrating the original version to Github, so we can just go ahead and work on the learning goals. 
However, I think the learning goals in chapter 1 motivation are hard to check if you have some training material. I added learning goals to chapter 3. I think they cover the essence of the chapter but LZ 3-1 is much too complex compared to the others.
I think we need to solve these challenges in a (remote) face-to-face meeting and discuss it.

**Comment by aheusingfeld** [comment]
Perfect. Then let's move forward in migrating the learning goals to the new structure on the master branch. I suggest whenever we want to add, remove, or refine one or multiple learning goals, we create a pull-request and discuss it there
