### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by ewolff** [isaqb-org/curriculum-flex#8]
The old (pre-GitHub) version of the FLEX curriculum is 1.1 . The versioning scheme seems to be changed, I am not sure why. At least, it would be interesting to know the differences between 1.1 and this version.

**Comment by aheusingfeld** [comment]
see #7. I already started to refactor the Learning Goals, that's the difference to version 1.1 and I asked _you_ whether we should continue or rather do a 1:1 transfer of the old outline
